version: "3.4"

services:
  poste:
    build: .
    environment:
      DATABASE_SETTING: docker
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: posteadmin
      DATABASE_PASSWORD: topsecretpassword
      DATABASE_NAME: poste
      DJANGO_USER: admin@email.com
      DJANGO_EMAIL: admin@email.com
      DJANGO_PASSWORD: admin1234
      DJANGO_SETTINGS_MODULE: PosteBackend.settings
    volumes:
        - static_volume:/usr/src/app/static
        - media_volume:/usr/src/app/media
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: posteadmin
      POSTGRES_PASSWORD: topsecretpassword
      POSTGRES_DB: poste
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "posteadmin", "-d", "poste"]
      interval: 5s
      timeout: 5s
      retries: 5

    ports:
      - "5432:5432"
    volumes:
      - data_volume:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    ports:
      - "80:80" # allows external access via port 80 (HTTP port)
      - "443:443" # allows external access via port 443 (HTTPS port)
      - "8000:80" # forwards existing requests on port 8000 to port 80 (app port - will be deprecated)
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/usr/share/nginx/html/static
      - media_volume:/usr/share/nginx/html/media
    depends_on:
      - poste

volumes:
  data_volume:
  static_volume:
  media_volume: