# Generated by Django 4.2.5 on 2023-11-05 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PosteAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='folderpermission',
            unique_together={('user', 'folder')},
        ),
    ]
