# Generated by Django 4.2.5 on 2023-10-15 02:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PosteAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='shared_users',
        ),
        migrations.CreateModel(
            name='FolderPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('viewer', 'Viewer'), ('editor', 'Editor'), ('full_access', 'Full Access')], max_length=12)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PosteAPI.folder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
