# Generated by Django 4.2.5 on 2023-09-20 01:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PosteAPI", "0002_folder_post_user_delete_testmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
