# Generated by Django 4.2.5 on 2023-11-16 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PosteAPI', '0003_tag_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='folder', to='PosteAPI.tag'),
        ),
    ]
