# Generated by Django 4.2.5 on 2024-01-28 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PosteAPI", "0004_folder_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="folder",
            name="is_root",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="folder",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_folders",
                to="PosteAPI.folder",
            ),
        ),
    ]
