# Generated by Django 4.2.5 on 2024-01-26 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PosteAPI", "0004_folder_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="folder",
            name="parent",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_folders",
                to="PosteAPI.folder",
            ),
        ),
    ]
