# Generated by Django 4.2.5 on 2024-02-20 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PosteAPI', '0004_folder_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='is_root',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='folder',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_folders', to='PosteAPI.folder'),
        ),
        migrations.AlterField(
            model_name='post',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='PosteAPI.folder'),
        ),
    ]
