# Generated by Django 4.2.5 on 2024-03-23 20:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PosteAPI", "0006_folder_created_at_post_created_at_user_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="folder",
            name="description",
            field=models.TextField(default=""),
        ),
    ]
